### ISSUE TITLE
DNS resolution failed when run with docker-compose

### ISSUE THREAD

**Issue by shimst3r** [adap/flower#938]
## Expected outcome

Running my `server.py` and `client.py` in different services using `docker-compose` should work.

## Actual outcome

The `client.py` cannot connect to the server started in `server.py` with the following error message:

```shell
debug_error_string = "{"created":"@1639410202.095422178","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":1324,"referenced_errors":[{"created":"@1639410202.095420088","description":"DNS resolution failed for service: server:5000","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":359,"grpc_status":14,"referenced_errors":[{"created":"@1639410202.095344709","description":"C-ares status is not ARES_SUCCESS qtype=A name=server is_balancer=0: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":698,"referenced_errors":[{"created":"@1639410202.090720089","description":"C-ares status is not ARES_SUCCESS qtype=AAAA name=server is_balancer=0: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":698}]}]}]}"
```

## Additional information

The server is started via:

```python
fl.server.start_server(
    f"{args.host}:{args.port}",
    strategy=strategy,
    config={"num_rounds": 10},
)
```

The client is started via:

```python
fl.client.start_numpy_client(
    f"{args.server}:{args.port}",
    client=SynthClient(model, data),
)
```

And the `docker-compose.yaml` looks like this:

```yaml
version: "3.9"
services:
  server:
    image: flower-fed
    build:
      context: .
      dockerfile: Dockerfile
    command: "python flower_fed/server.py 0.0.0.0 8080 404"
    hostname: "server"
    ports:
      - "5000:8080"
  client1:
    image: flower-fed
    command: "python flower_fed/client.py server 5000 42"
    depends_on:
      - "server"
  client2:
    image: flower-fed
    command: "python flower_fed/client.py server 5000 8008"
    depends_on:
      - "server"
```

## Notes

To be honest, I am not entirely sure whether this is a problem with flower or with my docker-compose setup. :flushed:
